female(pam).
male(tom).
male(bob).
female(liz).
female(ann).
female(pat).
male(jim).
parent(pam,bob).
parent(tom,bob).
parent(tom,liz).
parent(bob,ann).
parent(bob,pat).
parent(pat,jim).
mother(X,Y):-parent(X,Y),female(X).
child(Y,X):-parent(X,Y).
sister(X,Y):-parent(Z,X),parent(Z,Y),female(X).
anut(X,Y):-parent(Z,Y),sister(X,Z),female(X).

SSS
